### ISSUE TITLE
TypeError: 'DataContainer' object is not iterable

### ISSUE THREAD

**Issue by 1Hun0ter1** [yuantianyuan01/PreSight#3] opened 2024-09-26 13:47 UTC
When the training was nearly over for online mapping, an error occured in line 229 in StreamMapNet.py. TypeError: 'DataContainer' object is not iterable. How to solve it?

**Comment by 1Hun0ter1** [comment] 2024-09-29 03:11
Not only has the problem been found here, there may be more bugs in the published code.

**Comment by yuantianyuan01** [comment] 2024-09-30 06:03
Unfortunately I do not encounter the same issue. Please make sure you installed the conda environment following our instruction since a different version of mm* series may bring bugs.

**Comment by yuantianyuan01** [comment] 2024-09-30 06:10
I understand your frustration, but in order to help resolve the issue, I need more detailed information. When reporting bugs, it's essential to include details such as your environment (e.g., conda), the hardware you're using (GPUs), and the specific error or line where the issue occurs. This helps us investigate and address any problems more effectively. We appreciate your understanding and look forward to your detailed report.

**Comment by 1Hun0ter1** [comment] 2024-09-30 06:50
Thanks for your reply, I am using mmcv-full=1.5.3 but not mmcv=1.7.0. In this condition, I can also successfully test after updating the published codes.

**Comment by yuantianyuan01** [comment] 2024-10-01 06:27
Glad to hear the issue is resolved. I am closing this now, but feel free to reopen or open a new issue if anything else comes up. Thanks again.

**Closed as completed** 2024-10-01 06:27 UTC
